# fly.toml app configuration file generated for mongo-to-do on 2023-07-30T13:02:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mongo-to-do"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
